// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSfcEHUyDwkASsejYF0mpc0iYmrWanXYw',
    appId: '1:761970994409:web:6738f9a2e02803c2739478',
    messagingSenderId: '761970994409',
    projectId: 'campusguardian-ju',
    authDomain: 'campusguardian-ju.firebaseapp.com',
    storageBucket: 'campusguardian-ju.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6YR9D5-9s6-rlzaZni36c7o18mkMOf4',
    appId: '1:761970994409:android:c2493f8552d14569739478',
    messagingSenderId: '761970994409',
    projectId: 'campusguardian-ju',
    storageBucket: 'campusguardian-ju.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPDgn1Y61GPftjKBc_RVCqRf0ForqPhws',
    appId: '1:761970994409:ios:8e6d017f9a94c02c739478',
    messagingSenderId: '761970994409',
    projectId: 'campusguardian-ju',
    storageBucket: 'campusguardian-ju.firebasestorage.app',
    iosBundleId: 'com.example.campusGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPDgn1Y61GPftjKBc_RVCqRf0ForqPhws',
    appId: '1:761970994409:ios:8e6d017f9a94c02c739478',
    messagingSenderId: '761970994409',
    projectId: 'campusguardian-ju',
    storageBucket: 'campusguardian-ju.firebasestorage.app',
    iosBundleId: 'com.example.campusGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSfcEHUyDwkASsejYF0mpc0iYmrWanXYw',
    appId: '1:761970994409:web:4a9fdfa733ddf799739478',
    messagingSenderId: '761970994409',
    projectId: 'campusguardian-ju',
    authDomain: 'campusguardian-ju.firebaseapp.com',
    storageBucket: 'campusguardian-ju.firebasestorage.app',
  );
}
